const dbConfig=require("../config/db.config.js");
const mongoose=require("mongoose");
const db={};
db.mongoose=mongoose;
db.url=dbConfig.url;
db.companies=require("./company.model")(mongoose)
db.topics=require("./topic.model")(mongoose)
db.problems=require("./problem.model")(mongoose)
db.webads=require("./webad.model")(mongoose)
db.placementTips=require("./placementTips.model")(mongoose)
module.exports=db;
